my_app/urls.py
from django.urls import path
#  imports views from the current app directory
from . import views

# Namespace for this app's URL patterns to avoid conflicts with other apps
app_name = 'my_site'

urlpatterns = [
    # Define URL patterns, mapping routes to views with a name for reverse URL lookup
    path('', views.example_view, name='example'),
    path('variable', views.variable_view, name='variable')
]

my_site/urls.py
from django.contrib import admin
from django.urls import include, path
from my_app.views import homepage

urlpatterns = [
    path('', homepage, name='home'),
    path('admin/', admin.site.urls),
    #my app to include urls from my_app.urls
    path('my_app/',include('my_app.urls'))
]
handler404 = 'my_site.views.my_custom_page_not_found_view'

my_app/models.py
from django.db import models

# Create your models here.

my_app/views.py
from django.shortcuts import render

# Create your views here.
def example_view(request):
    return render(request, 'my_app/example.html')

def variable_view(request):
    my_var = {'first_name': 'tim', 'last_name': 'minchin',
    'some_list':[1,2,3], 'some_dict':{'inside_key':'inside_value'},
    'list_with_spaces': 'This String Had Spaces Before The Cut Filter'}

    # my_var contains the data rendered on variable.html making it dynamic.
    return render(request,'my_app/variable.html', context=my_var)

def homepage(request):
    return render(request, 'my_app/home.html')

my_site/views.py
from django.shortcuts import render

# custom view for a 404 error page not found.
def my_custom_page_not_found_view(request,exception):

    return render(request,'404.html', status=404)

my_app/templates/my_app/example.html
{% comment %} inherits the structure of a parent template {% endcomment %}
{% extends "base.html" %}

{% comment %} defines content to replace a block in the parent template {% endcomment %}
{% block content %}
<h1>EXAMPLE PAGE</h1>
{% comment %} pattern for url {% url 'namespace:route_name'%} {% endcomment %}
<a href="{% url 'my_site:variable' %}">click me to go to variable</a>
{% endblock content %}

my_app/templates/my_app/home.html
{% extends "base.html" %}
{% comment %} adding a static file to the homepage {% endcomment %}
{% load static %}
{% block content %}
<h1>Homepage</h1>
<img src="{% static 'my_app/django.jpg'%}" alt="image" style="width: 200px; height: auto;">
{% endblock content %}

my_app/templates/my_app/variable.html
{% comment %}inherits the structure of a parent template, block names must match {% endcomment %}
{% extends "base.html" %}

{% comment %} defines content to replace a block in the parent template {% endcomment %}
{% block content %}
<h1>VARIABLE PAGE</h1>
    <H2>{{first_name|capfirst}} {{last_name|capfirst}}</H2>
    <h2>{{some_list.1}}</h2>
    <h2>{{some_dict.inside_key}}</h2>
    <h2>{{list_with_spaces|cut:' '}}</h2>
    
    {% comment %} Django tags {% endcomment %}
    <h1>Django Tags</h1>
    {% comment %} Looping a List {% endcomment %}
    <ul>
    {% for num in some_list %}
        <li>{{num}}</li>
    {% endfor %}
    </ul>

    {% comment %} Looping a Dictionary {% endcomment %}
    {% for key,value in some_dict.items %}
        <h1>{{key}} {{value}}</h1>
    {% endfor %}

    {% comment %} for loop and if else {% endcomment %}
    <ul>
    {% for num in some_list %}
    {% if num == 2  %}
    <li>Two</li>
    {% else %}
    <li>{{num}}</li>
    {% endif %}
    {% endfor %}
    </ul>
{% endblock content %}

templates/base.html
{% comment %} html template includes things like navebar footer sitemap  {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% comment %} structure of template the block is inserted between the nav and fotter in the below case. {% endcomment %}
    <h1>This is a navbar</h1>
    {% block content %}
    {% endblock content %}
    <h1>This is a footer</h1>
</body>
</html>